const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
const FILTER_PRODUCTS = 'FILTER_PRODUCTS';
const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
const FETCH_PRODUCTS_BY_ID = 'FETCH_PRODUCTS_BY_ID';

export { FETCH_PRODUCTS, FILTER_PRODUCTS, UPDATE_PRODUCT, FETCH_PRODUCTS_BY_ID };